### ISSUE TITLE
Can't run 'reaction run' on window

### ISSUE THREAD

**Issue by naveen1941** [reactioncommerce/reaction-cli#36]
I have followed instructions given on official site to setup app on my windows 10 machine.

reaction init - is successful > then i did cd reaction/ then "reaction run"

but when I do "reaction run" I am getting the following message.
**************************************************************************************
This CLI tool has been deprecated in favor of the reaction-cli Node module. 
More info at https://www.npmjs.com/package/reaction-cli

You can install it by running:

npm install -g reaction-cli

Then you can see the usage info by running 'reaction --help'
**************************************************************************************
Note: reaciton -v

Node: 4.2.4 
NPM: 5.0.3 
Meteor Node: 4.8.2 
Meteor NPM: 4.5.0 
Reaction CLI: 0.9.3

**Comment by jshimko** [comment]
Sounds like your cmd prompt is running the [legacy bash script in the root of the Reaction project](https://github.com/reactioncommerce/reaction/blob/master/reaction) instead of using `reaction-cli`.  Try deleting that file and running it again.  

Not sure why that would happen for you when no other Windows users have reported it, so maybe there's something wrong with your [`$PATH`](http://www.linfo.org/path_env_var.html).  But I guess if running `reaction -v` works, that's clearly not the problem.
