### ISSUE TITLE
Managed Platform Command - Auto response 

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction-cli#41]
For non managed platform users, we would like to have an auto response message for any user that uses any of the following commands: 
`register    
login      
whoami     
keys        
apps        
deploy     
env         
domains     
env       
keys        
open        
whoami `     

Message: 
**This command requires being logged into the managed platform. Learn more: https://reactioncommerce.com/hosting**

**Comment by jshimko** [comment]
Let me know when that link is live and I'll add it.  (currently a dead end 404 page)

**Comment by cindyfirestone** [comment]
@jshimko The link is now live! https://reactioncommerce.com/hosting

**Comment by cindyfirestone** [comment]
Can you use this bit.ly link instead so we can track clicks? 
http://getrxn.io/reaction-platform

**Comment by jshimko** [comment]
This has been added for all platform commands.  However, I had to add a bit of a variation because you need to account for the possibility that the user may have an account but just isn't logged in.  So the updated output when you run a platform command while not logged in is:

![blank](https://user-images.githubusercontent.com/3077956/32082158-8be3ec50-ba6e-11e7-9bf7-070a97c6b19d.png)

**Comment by jshimko** [comment]
This is all set as of `v0.19.1`.
