### ISSUE TITLE
Address npm dependency issues found in master branch [Opened by bitHound]

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-cli#45]
<p>bitHound discovered:</p> <ul> <li>1 package with at least one security vulnerability.</li> <li>1 unused package.</li> </ul> <p>For details go to <a href="https://www.bithound.io/github/reactioncommerce/reaction-cli/master/dependencies/npm">bitHound</a>.</p>

**Comment by aaronjudd** [comment]
This is a critical impact issue and needs an update. Can you please update the status?

**Comment by jshimko** [comment]
I have to replace all usage of shelljs with native Node libs.  The issue is only with the `exec` method in shelljs, but we're going to see the error whether we're using that method or not.  So that leaves us with no other option but to replace the entire lib.  That's absolutely the plan, but it's probably going to be at least a half day of work once I get to it (which was planned for this week).

**Comment by aaronjudd** [comment]
Status of replacing shelljs?

**Comment by jshimko** [comment]
This was a bit of a project, but it has finally been completed and released in `v0.22.0`.  And `shelljs` has been entirely removed.

https://github.com/reactioncommerce/reaction-cli/commit/ae564e284156e2f6ff6d00dcaffbb27be0617cb3
